"""Autogenerated strenum."""

from enum import StrEnum


class BrokersType(StrEnum):
    """Brokers options."""

    KAFKA = "kafka"
    LOCAL = "local"
    RABBITMQ = "rabbitmq"

    @classmethod
    def _missing_(cls, value: object) -> None:
        options = ", ".join([f"'{item.value}'" for item in cls])
        raise ValueError(f"'{value}' is not a valid {cls.__name__}. Allowed options are: [{options}]")
