"""Autogenerated strenum."""

from enum import StrEnum


class ThreadsType(StrEnum):
    """Types of threads."""

    INVENTORY = "inventory"
    NOTIFICATION = "notification"
    ORDER = "order"
    PAYMENT = "payment"

    @classmethod
    def _missing_(cls, value: object) -> None:
        options = ", ".join([f"'{item.value}'" for item in cls])
        raise ValueError(f"'{value}' is not a valid {cls.__name__}. Allowed options are: [{options}]")
