"""Autogenerated strenum."""

from enum import StrEnum


class PaymentStatusEnum(StrEnum):
    """Statuses for card payments."""

    FAILED = "failed"
    PAID = "paid"
    PAYING = "paying"
    PENDING = "pending"
    UNPAID = "unpaid"

    @classmethod
    def _missing_(cls, value: object) -> None:
        options = ", ".join([f"'{item.value}'" for item in cls])
        raise ValueError(f"'{value}' is not a valid {cls.__name__}. Allowed options are: [{options}]")
